main: nl.parrotlync.hiddenmickeys.HiddenMickeys
name: ${artifactId}
version: ${version}
description: ${description}
api-version: 1.15
author: ParrotLync
depend: [PlaceholderAPI]
commands:
  hiddenmickeys:
    description: Main command
    usage: /hiddenmickeys
    aliases: [hm]
permissions:
  hiddenmickeys.admin:
    default: op
    description: Create or remove HiddenMickeys
